[package]
name = "codec"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
byteorder = "1.2"
failure = "0.1"
libc = "0.2"
static_assertions = { version = "1.0", features = ["nightly"] }
tikv_alloc = { path = "../tikv_alloc" }

[dev-dependencies]
panic_hook = { path = "../panic_hook" }
protobuf = "2"
bytes = "0.4.10"
rand = "0.7"
