log-level = "info"
backtrace-dir = "./"
log-file = "./thumbnail.log"

[storage.reading-threadpool]
name = "reading-pool"
high-concurrency = 2
normal-concurrency = 1
low-concurrency = 1
max-tasks-per-worker-high = 500
max-tasks-per-worker-normal = 300
max-tasks-per-worker-low = 200
stack-size = "1024MB"

[storage.writing-threadpool]
name = "writing-pool"
high-concurrency = 2
normal-concurrency = 1
low-concurrency = 1
max-tasks-per-worker-high = 500
max-tasks-per-worker-normal = 300
max-tasks-per-worker-low = 200
stack-size = "1024MB"

[storage]
cache-dir = "/home/vagrant/example-io/cache"

[metric]
address = "0.0.0.0:9090"

[http-service]
addr = "0.0.0.0:8080"
http-worker = 10
client-shutdown = "10s"