[package]
name = "file_system"
version = "0.1.0"
edition = "2018"
publish = false

[features]
bcc-iosnoop = ["bcc"]

[dependencies]
collections = { path = "../collections" }
crc32fast = "1.2"
crossbeam-utils = "0.8.0"
fs2 = "0.4"
lazy_static = "1.3"
libc = "0.2"
nix = "0.19"
openssl = "0.10"
prometheus = { version = "0.10", features = ["nightly"] }
prometheus-static-metric = "0.4"
tikv_alloc = { path = "../tikv_alloc" }
cibo_util = { path = "../cibo_util" }
variant_count = "1.0.0"

[dev-dependencies]
rand = "0.7"
tempfile = "3.0"
maligned = "0.2.1"

[target.'cfg(target_os = "linux")'.dependencies]
bcc = { version = "0.0.30", optional = true }

