[package]
name = "engine_rocks"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "keys/protobuf-codec",
  "txn_types/protobuf-codec",
  "raft/protobuf-codec",
  "kvproto/protobuf-codec",
]
prost-codec = [
  "keys/prost-codec",
  "txn_types/prost-codec",
  "raft/prost-codec",
  "kvproto/prost-codec",
]
jemalloc = ["rocksdb/jemalloc"]
portable = ["rocksdb/portable"]
sse = ["rocksdb/sse"]

[dependencies]
encryption = { path = "../encryption" }
engine_traits = { path = "../engine_traits" }
keys = { path = "../keys" }
num_cpus = "1"
prometheus = { version = "0.10", features = ["nightly"] }
prometheus-static-metric = "0.4"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "d592f88e4dbba5eb439998463054f1a44fbf17b9" }
tikv_alloc = { path = "../tikv_alloc" }
cibo_util = { path = "../cibo_util" }
txn_types = { path = "../txn_types"}
lazy_static = "1.4.0"
log_wrappers = { path = "../log_wrappers" }
time = "0.1"
configuration = { path = "../configuration" }
tempfile = "3.0"
serde = "1.0"
serde_derive = "1.0"
kvproto = { path = "../kvproto", default-features = false }
raft = { version = "0.6.0-alpha", default-features = false }
protobuf = "2"

[dependencies.rocksdb]
git = "https://github.com/tikv/rust-rocksdb.git"
package = "rocksdb"
features = ["encryption", "static_libcpp"]

[dev-dependencies]
kvproto = { path = "../kvproto", default-features = false }
rand = "0.7"
toml = "0.5"
